HUMANE_SERVER_PORT: 3000
logLevel: info
baseUrl : http://localhost:3000/
esConfig:
  url: http://localhost:9200
  maxSockets: 20
  maxFreeSockets: 5
  timeout: 60000
  keepAliveTimeout: 30000
redisSentinelConfig:
    name: books-dev-redis-master
    endpoints: [{host: '192.168.10.98', port: 20001},{host: '192.168.10.90', port: 20000}]
redisConfig:
  host: 127.0.0.1
  port: 6379
  connect_timeout: 10000
  retry_max_delay: 50000
locksConfig:
  type: redis # allowed values: redis, local, or null (==local)
  timeout: 10000
  retries: 1000
  delay: 100
cacheConfig:
  type: redis # allowed values: redis, local, or null (==local)
  flushTimeout: 30000 # 10 seconds